version: "3.8"

services:
  mongo:
    image: mongo
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: project
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
